### ISSUE TITLE
cfbfastR::load_cfbd_pbp(seasons) issue

### ISSUE THREAD

**Issue by ednabaestmode** [saiemgilani/cfbfastR#25]
**Describe the bug**
When attempting to pull pbp data from 2002-2020 using the function below and am receiving the error below. 

**function**
pbp <- data.frame()
seasons <- 2002:2020
progressr::with_progress({
  future:: plan("multisession")
  pbp <-cfbfastR::load_cfbd_pbp(seasons)
})

Error: 'load_cfbd_pbp' is not an exported object from 'namespace:cfbfastR

https://twitter.com/SaiemGilani/status/1390423040077537285?s=20

**Comment by ednabaestmode** [comment]
Thanks for pointing that out. I was adjusting it to see if the function would work with a "d" added. But I am still receiving the same error without the d. 

pbp <- data.frame()
seasons <- 2002:2020
progressr::with_progress({
  future:: plan("multisession")
  pbp <-cfbfastR::load_cfb_pbp
})

Error: 'load_cfb_pbp' is not an exported object from 'namespace:cfbfastR'

**Comment by saiemgilani** [comment]
well, one thing, i haven't added the ability to go back to 2002 just yet. 
you still need the seasons argument.
https://saiemgilani.github.io/cfbfastR/articles/intro.html#the-fastr-way-load_cfb_pbp-7-seasons-1-1-5-minutes
