### ISSUE TITLE
`espn_ratings_fpi` not in CRAN install

### ISSUE THREAD

**Issue by math-mcshane** [saiemgilani/cfbfastR#51]
**Describe the bug**
`espn_ratings_fpi` not in CRAN install

**To Reproduce**
```
install.packages("cfbfastR")
library(cfbfastR)
cfbfastR::espn_ratings_fpi(year = 2018)
```

**Expected behavior**
For this function to be available
https://saiemgilani.github.io/cfbfastR/reference/espn_ratings.html 

**Screenshots**
![image](https://user-images.githubusercontent.com/48807452/140540343-d5776209-1f8a-4586-8ac9-a6f4bbb5e888.png)

**Desktop (please complete the following information):**
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

other attached packages:
[1] cfbfastR_1.6.4
```

**Comment by saiemgilani** [comment]
Curious. I bet I had a reason. The function needed to be rewritten with a better endpoint, I bet. Will review in the coming days and fix upon next release

**Comment by math-mcshane** [comment]
It looks like it failed one of the checks (MacOS)
https://github.com/saiemgilani/cfbfastR/blob/master/R/espn_ratings_fpi.R
