### ISSUE TITLE
Request Failed [500] -> 2021 Data

### ISSUE THREAD

**Issue by TJLSmith0831** [saiemgilani/cfbfastR#55]
I have been using cfbfastR for the past couple of weeks and have loaded data from 2015 to 2021. Today however I have been unable to load 2021 data and I believe you should look into this.

**Comment by Kazink36** [comment]
How are you accessing the data (which functions)? It's only the 2021 data?

**Comment by TJLSmith0831** [comment]
Using cfbd_game_info() and yes it’s just 2021. I can pull data from 2015-2020 without issue.

Tristan Smith
-----------------
Trinity University '22
Business Analytics and Technology / Sports Management
Delta Sigma Pi - 2021 Pi Omega Chapter President
-----------------
________________________________

**Comment by Kazink36** [comment]
That's strange as it works for me, 500-series errors tend to indicate “it’s the server’s fault, not yours” so it may just be on collegefootballdata.com's side and the operator is busy celebrating Michigan's win.

**Comment by TJLSmith0831** [comment]
Yep it’s working now!

Tristan Smith
-----------------
Trinity University '22
Business Analytics and Technology / Sports Management
Delta Sigma Pi - 2021 Pi Omega Chapter President
-----------------
________________________________
